### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by anamariaUIC** [kwanjeeraw/lmm2met#1]
Hello,

does the output of fitting a model with your software included Beta and SE?

Thanks
Ana

**Comment by kwanjeeraw** [comment]
It returns standard output of mixed effect modeling as the following figure. 
![mixmodel](https://user-images.githubusercontent.com/9489075/124060017-4c796980-da56-11eb-83bd-6070b4b195aa.png)

**Comment by anamariaUIC** [comment]
Thanks. So the Estimate column is Beta? Can the output be saved in a data frame? I just need Standard Error and Beta column. How do I save just those in a data frame?

Sent from my iPhone

On 30 Jun 2021, at 22:24, Kwanjeera W ***@***.***> wrote:

﻿

It returns standard output of mixed effect modeling as the following figure.
[mixmodel]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F9489075%2F124060017-4c796980-da56-11eb-83bd-6070b4b195aa.png&data=04%7C01%7Canamaria%40uic.edu%7Cdaad857b106a44e6453008d93c3fad9d%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637607066469485921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=F%2F3SQak8P3lGr0qVTA05KKf0xdcq1dG1kHmTo8IlNRc%3D&reserved=0>

**Comment by kwanjeeraw** [comment]
Yes, you can do it with this command for each variable X1 ->
summary(fitMet$completeMod[[1]])$coefficients

**Comment by anamariaUIC** [comment]
Thank you so much for getting back to me, I am looking forward to use this software in my next publication. One more question: I do have a nested, matched case/control study design. So I have 99 cases and 99 controls. I am wondering can I still fit my model with your software (given my study design) if I want to control for: age, sex, BMI and the first 2 surrogate variables. Would my model look like this:

fitMet = fitLmm(fix=c('Sex','Age','BMI','SV1,'SV2'), random='(1|ID)', data=df, start=10)

I want to be able to identify metabolites that differ between cases (retinopathy) and controls (no retinopathy)

So in the random ID parameter, shouldn't I have the name of the column where I have disease status for each subject, or in other words should my pheno column be random variable?

Can you please explain me how would I run this?

Many thanks
Ana

**Comment by kwanjeeraw** [comment]
The random effect for subject variation e.g.  assuming a different baseline.
In your case, disease condition is the fixed effect because you are interested in metabolite differences between those disease conditions.
So, the command will look like this, which will build a model for each metabolite.
fitMet = fitLmm(fix=c('Sex','Age','BMI','SV1,'SV2','disease_condition'), random='(1|ID)', data=df, start=10)

The following tutorials provide nice introduction for linear mixed effect models.
https://bodowinter.com/tutorial/bw_LME_tutorial1.pdf
https://bodowinter.com/tutorial/bw_LME_tutorial2.pdf

**Comment by anamariaUIC** [comment]
Thank you so much for clarifying that and sharing those links, I will read them carefully. One last question: does it make any difference for this regression that the design of my study is matched nested case control design (as I outlined in my previous message)?

**Comment by kwanjeeraw** [comment]
random='(1|ID)' is the term for the matched design.
The ID column provides information on matched samples e.g.
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Mint/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Mint/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ID | Group | Age
-- | -- | --
1 | Case | 50
2 | Case | 60
3 | Case | 70
1 | Control | 50
2 | Control | 60
3 | Control | 70



</body>

</html>

**Comment by anamariaUIC** [comment]
Hi Kwanjeera,

I plan to use your software lmm2met to model log transformed metabolite levels using linear mixed models as implemented in lmm2met.
Can you please confirm if this can be legitimate use of this software? I am a bit confused because you talk about removing noise from the data using this software in the associated paper.
In other words can I use lmm2met to fit Linear Mixed-Effects Model just as I would do using lme4 or your would recommend using lme4 for fitting the model?

Thanks
Ana

On Jul 11, 2021, at 11:53 PM, Kwanjeera W ***@***.******@***.***>> wrote:



random='(1|ID)' is the term for the matched design.
The ID column provides information on matched samples e.g.

<style> </style>
ID      Group   Age
1       Case    50
2       Case    60
3       Case    70
1       Control 50
2       Control 60
3       Control 70

**Comment by kwanjeeraw** [comment]
Yes. You can use the package to do linear mixed-effect modeling. I our paper we applied this concept to process noise in our data.
Our package was implemented on lme4, so it follows lme4 formulas for the random-effects term.
You can observe standard output of the mixed effect model for each metabolite, e.g. summary(fitMet$completeMod[[1]]) or 
get fixed-effects coefficients and p-values with getFixCoeff(fitMet).

**Comment by anamariaUIC** [comment]
Thank you so much for clarifying that!

On Sep 21, 2021, at 2:13 AM, Kwanjeera W ***@***.******@***.***>> wrote:



Yes. You can use the package to do linear mixed-effect modeling. I our paper we applied this concept to process noise in our data.
Our package was implemented on lme4, so it follows lme4 formulas for the random-effects term.
You can observe standard output of the mixed effect model for each metabolite, e.g. summary(fitMet$completeMod[[1]]) or
get fixed-effects coefficients and p-values with getFixCoeff(fitMet).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkwanjeeraw%2Flmm2met%2Fissues%2F1%23issuecomment-923704320&data=04%7C01%7Canamaria%40uic.edu%7C07451388286b4dad240a08d97ccf5165%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637678052142070589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WVwYJ%2By57QACiPyuyOqXB9jNYkT0rGgD9kW3DlcZBgU%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHBH5DCPMBOPBVUYJIB4E3UDAWBXANCNFSM47TF6V5Q&data=04%7C01%7Canamaria%40uic.edu%7C07451388286b4dad240a08d97ccf5165%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637678052142070589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XwDhF3Pwb4IoQav%2FqWRAd88vU6OzlgAASEOpBxIUSrQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Canamaria%40uic.edu%7C07451388286b4dad240a08d97ccf5165%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637678052142080583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VAiDgbx4YJOpDBMtsabV71YqwZeFhJpbVwyqJNnyz9E%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Canamaria%40uic.edu%7C07451388286b4dad240a08d97ccf5165%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637678052142080583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AVl3FiJacdjYKV0DYglbREy%2FvQmsbcvRan2G9BXvFv8%3D&reserved=0>.
